name: Main Pipeline

on: push

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint:all

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
